# Generated by Django 4.2.1 on 2023-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_demande', models.CharField(max_length=100)),
                ('selected_interface', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('filter', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Capture',
        ),
    ]
