# Generated by Django 4.2.1 on 2023-09-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_capturerequest_delete_capture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturerequest',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='capturerequest',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
